# Generated by Django 3.1.2 on 2020-11-07 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='csverrorfile',
            old_name='commit',
            new_name='commit_processing',
        ),
    ]
