# Generated by Django 3.1.2 on 2020-11-06 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auther_book_fileupload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='auther',
        ),
        migrations.DeleteModel(
            name='FileUpload',
        ),
        migrations.DeleteModel(
            name='Auther',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
