# Generated by Django 3.1.2 on 2020-11-07 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20201107_1527'),
    ]

    operations = [
        migrations.RenameField(
            model_name='csverrorfile',
            old_name='commit_processing',
            new_name='commited',
        ),
    ]
