# Generated by Django 3.1.2 on 2020-11-24 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20201107_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='csverrorfile',
            name='message',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
